#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
LUA_SRC="$SCRIPT_DIR/extension/vlcaption.lua"
CONFIG_DIR="$HOME/.config/vlcaption"

echo "=== VLCaption Installer ==="
echo ""

# 1. Detect OS and set VLC extensions directory
case "$(uname -s)" in
    Darwin)
        VLC_EXT_DIR="$HOME/Library/Application Support/org.videolan.vlc/lua/extensions"
        ;;
    Linux)
        VLC_EXT_DIR="$HOME/.local/share/vlc/lua/extensions"
        ;;
    MINGW*|MSYS*|CYGWIN*)
        VLC_EXT_DIR="$APPDATA/vlc/lua/extensions"
        ;;
    *)
        echo "Warning: Unknown OS. Please manually copy vlcaption.lua to your VLC extensions directory."
        VLC_EXT_DIR=""
        ;;
esac

# 2. Install Python package (always in a venv)
echo "Installing Python package..."
if command -v uv &> /dev/null; then
    (cd "$SCRIPT_DIR" && uv sync)
    SERVER_BIN="$SCRIPT_DIR/.venv/bin/vlcaption-server"
    echo "  Done (uv sync)."
else
    echo "  uv not found, using pip with venv..."
    if [ ! -d "$SCRIPT_DIR/.venv" ]; then
        python3 -m venv "$SCRIPT_DIR/.venv"
        echo "  Created venv at $SCRIPT_DIR/.venv"
    fi
    "$SCRIPT_DIR/.venv/bin/pip" install -e "$SCRIPT_DIR"
    SERVER_BIN="$SCRIPT_DIR/.venv/bin/vlcaption-server"
    echo "  Done (pip install in venv)."
fi
echo ""

# 3. Create launcher script
echo "Creating server launcher..."
mkdir -p "$CONFIG_DIR"

cat > "$CONFIG_DIR/launch-server.sh" << LAUNCHER_EOF
#!/usr/bin/env bash
# Auto-generated by VLCaption installer. Re-run install.sh to update.
exec "$SERVER_BIN" "\$@"
LAUNCHER_EOF
chmod +x "$CONFIG_DIR/launch-server.sh"
echo "  Launcher: $CONFIG_DIR/launch-server.sh"
echo "  Server binary: $SERVER_BIN"
echo ""

# 4. Install Lua extension
if [ -n "$VLC_EXT_DIR" ]; then
    echo "Installing VLC Lua extension..."
    mkdir -p "$VLC_EXT_DIR"
    cp "$LUA_SRC" "$VLC_EXT_DIR/vlcaption.lua"
    echo "  Installed to: $VLC_EXT_DIR/vlcaption.lua"
else
    echo "Skipping VLC extension install (unknown OS)."
    echo "Please copy extension/vlcaption.lua to your VLC extensions directory."
fi
echo ""

echo "=== Installation complete ==="
echo ""
echo "Usage:"
echo "  1. Open VLC and play a media file"
echo "  2. Go to VLC > Extensions > VLCaption - Auto Subtitles"
echo "  3. Select a model and click 'Generate Subtitles'"
echo ""
echo "The server starts automatically when you generate subtitles."
echo "It shuts down when you close VLC."
