"""Install the VLC extension and server launcher from a pip/uv install.

Lets PyPI users set up the full extension experience without cloning the
repo: copies the bundled Lua extension into VLC's extensions directory and
writes the launcher script the extension uses to auto-start the server.
"""

from __future__ import annotations

import logging
import os
import shutil
import sys
import sysconfig
from argparse import ArgumentParser
from importlib import resources

logger = logging.getLogger(__name__)

LAUNCHER_DIR = os.path.expanduser("~/.config/vlcaption")


def vlc_extensions_dir() -> str:
    """VLC's per-user Lua extensions directory for this OS.

    Raises:
        RuntimeError: On platforms where the location is unknown.
    """
    if sys.platform == "darwin":
        return os.path.expanduser("~/Library/Application Support/org.videolan.vlc/lua/extensions")
    if sys.platform.startswith("linux"):
        return os.path.expanduser("~/.local/share/vlc/lua/extensions")
    if sys.platform == "win32":
        appdata = os.environ.get("APPDATA")
        if appdata:
            return os.path.join(appdata, "vlc", "lua", "extensions")
    raise RuntimeError(f"Don't know VLC's extensions directory on {sys.platform!r}; copy the .lua file manually")


def find_server_bin() -> str:
    """Locate the vlcaption-server console script installed alongside us.

    Raises:
        RuntimeError: If the script cannot be found.
    """
    candidates = [
        os.path.join(sysconfig.get_path("scripts"), "vlcaption-server"),
        shutil.which("vlcaption-server") or "",
    ]
    for candidate in candidates:
        if candidate and os.path.isfile(candidate):
            return candidate
    raise RuntimeError("Could not locate the vlcaption-server executable; is vlcaption fully installed?")


def install_extension() -> str:
    """Copy the bundled Lua extension into VLC's extensions directory."""
    ext_dir = vlc_extensions_dir()
    os.makedirs(ext_dir, exist_ok=True)
    lua = resources.files("vlcaption").joinpath("extension/vlcaption.lua").read_text(encoding="utf-8")
    target = os.path.join(ext_dir, "vlcaption.lua")
    with open(target, "w", encoding="utf-8") as f:
        f.write(lua)
    return target


def install_launcher(server_bin: str) -> str:
    """Write the launcher script the extension uses to start the server."""
    os.makedirs(LAUNCHER_DIR, exist_ok=True)
    target = os.path.join(LAUNCHER_DIR, "launch-server.sh")
    with open(target, "w", encoding="utf-8") as f:
        f.write(
            "#!/usr/bin/env bash\n"
            "# Auto-generated by vlcaption-install. Re-run it to update.\n"
            "# VLC launches this with a minimal GUI environment whose PATH lacks\n"
            "# Homebrew, hiding ffmpeg (needed to decode audio) from the engines.\n"
            'export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"\n'
            f'exec "{server_bin}" --exit-with-vlc "$@"\n'
        )
    os.chmod(target, 0o755)
    return target


def main() -> None:
    """Entry point for vlcaption-install."""
    parser = ArgumentParser(description="Install the VLC extension for a pip/uv-installed vlcaption")
    parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(message)s")

    try:
        lua_path = install_extension()
        logger.info("Installed VLC extension: %s", lua_path)
        server_bin = find_server_bin()
        launcher = install_launcher(server_bin)
        logger.info("Installed server launcher: %s (server: %s)", launcher, server_bin)
    except RuntimeError as e:
        parser.error(str(e))

    logger.info("")
    logger.info("Done. Restart VLC, then: VLC > Extensions > VLCaption - Auto Subtitles")
    logger.info("Or skip the extension entirely with watch mode: vlcaption-watch")


if __name__ == "__main__":
    main()
